### ISSUE TITLE
Erweiterung 'Tracks2Map' konnte nicht geladen werden

### ISSUE THREAD

**Issue by Nacktiv** [hhtznr/JOSM-Tracks2Map-Plugin#1]
SCHWERWIEGEND: org.openstreetmap.josm.plugins.PluginException: In der Erweiterung Tracks2Map ist ein Fehler aufgetreten.. Ursache: java.lang.reflect.InvocationTargetException. Ursache: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "gpxDirectoryName" is null
org.openstreetmap.josm.plugins.PluginException: In der Erweiterung Tracks2Map ist ein Fehler aufgetreten.
        at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:387)
        at org.openstreetmap.josm.plugins.PluginHandler.loadPlugin(PluginHandler.java:846)
        at org.openstreetmap.josm.plugins.PluginHandler.loadPlugins(PluginHandler.java:931)
        at org.openstreetmap.josm.plugins.PluginHandler.loadLatePlugins(PluginHandler.java:983)
        at org.openstreetmap.josm.gui.MainApplication.loadLatePlugins(MainApplication.java:1257)
        at org.openstreetmap.josm.gui.MainApplication.mainJOSM(MainApplication.java:962)
        at org.openstreetmap.josm.gui.MainApplication$3.processArguments(MainApplication.java:277)
        at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:742)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:382)
        ... 7 more
Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "gpxDirectoryName" is null
        at hhtznr.josm.plugins.tracks2map.Tracks2MapPlugin.setGPXDirectoryFromPreferences(Tracks2MapPlugin.java:51)
        at hhtznr.josm.plugins.tracks2map.Tracks2MapPlugin.<init>(Tracks2MapPlugin.java:35)
        ... 13 more

**Comment by Nacktiv** [comment]
Debian Bookworm, KDE Desktop, Wayland, Java 17.0.9, JOSM 18940

**Comment by hhtznr** [comment]
Thank you for reporting this bug. Fixed with commit 435a0379c4554f1d0539ca330e429435853f975c and [release 0.3.1](https://github.com/hhtznr/JOSM-Tracks2Map-Plugin/releases/tag/v0.3.1) .
